### ISSUE TITLE
Release timeline of Pre-trained model

### ISSUE THREAD

**Issue by setotaku0515** [abdoelsayed2016/TNCR_Dataset#1]
Hi,

Thank you for sharing your wonderful source code and pre-trained model.
If you have any plans to release new pre-trained model, could you give me some information about that?

Best regards 👍

**Comment by abdoelsayed2016** [comment]
yes we are working on vision transformer object detection model, and some deep learning model 
in next months we will publish the results

**Comment by setotaku0515** [comment]
Thank you for your information :)

I checked pre-trained Deformable DETR has been released, but its backbone is only ResNet50.
Is this because more complicated backbone model caused overfitting?
Anyway, I'm looking forward to testing the new models!!

Thanks.

**Comment by abdoelsayed2016** [comment]
yes, we need to add also augmentation techniques to avoid overfitting

**Comment by setotaku0515** [comment]
I understand, thanks a lot.
