### ISSUE TITLE
Dataset download from Google Drive

### ISSUE THREAD

**Issue by setotaku0515** [abdoelsayed2016/TNCR_Dataset#2]
Hi,

I downloaded TNCR dataset from Google drive and checked contents (all 5 parts).
The 1st part of them contains 6,621 images and annotations, and I think it means all data of TNCR are included in the 1st part.
Could you give more information about each part of them?

Best regards 👍

**Comment by abdoelsayed2016** [comment]
you cant unrar part 1 without other parts I think

**Comment by setotaku0515** [comment]
Thank you for your reply.
Honestly speaking, I didn't understand decompression method correctly.
Now, I got correct images and annotations from Google Drive.
