### ISSUE TITLE
Question about the calculation of 50%:95% in the tables.

### ISSUE THREAD

**Issue by uobinxiao** [abdoelsayed2016/TNCR_Dataset#4]
It seems that 50%:95% in the paper, such as Table 6, is not the average score. Is it correct?

**Comment by abdoelsayed2016** [comment]
Not the average, it is calculated by the script in mmdetection

**Comment by uobinxiao** [comment]
Thanks for your quick reply. I calculate these values of Table 6 and Table 11. It seems that in the Table 11, it means the average score. What is it if it is not the average score? A weighted avarege version?

**Comment by abdoelsayed2016** [comment]
Sorry I was a long time, 2 years ago, I didn't remember exactly, but as I remember that we specified it in code 50:95 in mmdetection

**Comment by abdoelsayed2016** [comment]
`python mmdetection/tools/test.py 'configfile.py' 'model'  --eval  bbox `

Please read in mmdetetion test file. Careful about the version because mmdetection now has a new version

**Comment by uobinxiao** [comment]
I just check your configs files and saw this evaluation = dict(metric=['bbox', 'segm'],iou_thrs=[.50,.95]), this means the score of using 0.5 and 0.95 as threshold. So, I think 50%:95% in your paper means the mean value of (F1@0.5 + F1@0.95) /2, just use F1 as an example.
